# Based on .travis.yml in `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)

sudo: true

os:
  - linux
  - osx

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
  matrix:
    - LAZ_VER=1.4.4

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      env: LAZ_VER=1.4.4  LAZ_WINE=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
    - os: linux
      env: LAZ_VER=1.4.4  LAZ_WINE=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"

before_install:
    # Start virtual display server
  - sh -e /etc/init.d/xvfb start || true
  - sudo apt-get update && sudo apt-get install libxtst-dev libkeybinder-dev || true
  - cp Simba.inc ./Simba/Projects/Simba || true

install:
    # Install prerequisites (wine/fpc/lazarus)
  - ./autobuild/travis-lazarus/.travis.install.py

script:
  - $LAZ_WINE lazbuild $LAZ_OPT ./shenzi.lpi

notifications:
  irc:
    channels: "irc.rizon.net#simba"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"

deploy:
  provider: releases
  api_key:
    secure: wTcNqPmyjc1YAlR5Uud7WRzOYtgCzG4fWY4/WQeo4GNXy8HhNFGcTSf9hYpsh2nZxbBvOzpncNv+FUSGhJ1fpsON+wyPAtiD6M5xf3WcirPxDmWY2yzhUtoEMY5Ab6KVS8+KSfSwpKBCrRFZXMIUFLORCR9mWjiLSzRF+glTQEN7Mt8WRkkaziPqDgj0qcbNELn2/eB/DeXDk/aP8/dXSvLY4Vzk31GHyUigNmc84kieR1URjwDmomP55TZFyDzQHhEXKBOE/2oviRxcEH8ThNUjich7bD7+VgjbmOQNbqvNy7WK/A8IEIZKTQdaWaDdMYGRPa7/N7EZUW9W8lcAfIJ+OmRrklakMCVZDbEEEyaDrZoCDw62UDIaxiH6aBcGuBapc0mLAv6FIbKFTJpJ7R+8/4krTHyqvzMwvwCzSOV1YFi9FKzMVjCqUnhsfjVDinFWnjq1dxnFkUX3UhtJFNPIO+1QsWk+cQvPPIIpAI/FzkZX+RlqaK3tJdyi1Xe3NRphBC5zv1Kqcz43tgGQdI6Ffiocr8kKm
  file:
    - "Shenzi.i386-win32-debug.exe"
    - "Shenzi.x86_64-win64-debug.exe"
    - "Shenzi.i386-linux-debug"
    - "Shenzi.x86_64-linux-debug"
  skip_cleanup: true
  on:
    tags: true