# Based on .travis.yml in `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)

sudo: true
os: linux

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
    - LAZ_VER=1.4.4
  matrix:
    - OS="win32" CPU="i386" LAZ_WINE="wine" WINEARCH="win32" BINARYEXT=".exe"
    - OS="win64" CPU="x86_64" LAZ_WINE="wine" WINEARCH="win64" BINARYEXT=".exe"
#   - OS="linux" CPU="i386"
    - OS="linux" CPU="x86_64"

matrix:
  fast_finish: true

before_install:
  - sh -e /etc/init.d/xvfb start || true
  - sudo apt-get update && sudo apt-get install libxtst-dev libkeybinder-dev || true

install:
  - ./autobuild/travis-lazarus/.travis.install.py

before_script:
  - cp Simba.inc ./Simba/Projects/Simba || true
  - cp lape.inc ./Lape || true

script:
  - $LAZ_WINE lazbuild --os=$OS --cpu=$CPU ./shenzi.lpi
  - $LAZ_WINE lazbuild --os=$OS --cpu=$CPU --bm=Release ./shenzi.lpi

notifications:
  irc:
    channels: "irc.rizon.net#simba"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"

deploy:
  provider: releases
  api_key:
    secure: "S4qDiuC/vIRXe3XtRJCczG13GOLep8W7YOS7bUGr5amgNRT4ZYfnPicGwNgTco2v0dGrTq/4H95CYr+YwcdWQFs0iO6hCwvVEhgZ49KfGXxB+fulcUjAEG9xlKLvXf/+65SjV7UgcbizShixmo5KZr1z7Zg4R4jBAvRc4Xjco7k3UhTl/ZRaeDP4s9VNQ+l4XXv2XULHdaNWPQM0s4IvNh4CE070fok5Ve8czQ3e/kNUX2TD6kIgviuBy04VGeU/tgg1/LLmgJYXHODV4aRiBzfUb+2Bgk48RiHdgSuhKUaR0YPl1ASXbPwS88rLBdEqWZYmDZgKiNP9bU1W/tuwkuqyI8p3IQ/MnANxE/hx1Zpz9pu1ptrm/83GotGld/m15gwr5yqNE6PP97KR4OB6lFzZxL3PJ8KBHM2WD2pnliWWsdvV4nLozXcIupVZZbdXmP4XeJQJ96uXG8Auf3b+YYGZC8hOVeQgXQjE8f9JTftgVSk5+Lq8N31jCaNnS3l38h0QBJs9yeUyDgIyN+qcQjUanpWjSCCapAzgcA/4ms0rNW9XW2Uol5P7Hx+VW56LO3CiKJ2gSo4/7fAqNn5TTCDCBkh5Snid9O2dKEu/uGemvBC6Yt8vTj0ESltssyaNspy9WNasna6s+oVxIJaIfmCjjJjR2p2w6HNVsSsTgwI="
  file:
    - Shenzi.$CPU-$OS$BINARYEXT
    - Shenzi.$CPU-$OS-debug$BINARYEXT
  skip_cleanup: true
  on:
    tags: true
